version: 2
jobs:
  rspec:
    docker:
      - image: registry.opensuse.org/obs/server/unstable/container/sle12/sp3/images/x86_64/openbuildservice/frontend-base:latest
        environment:
          NOKOGIRI_USE_SYSTEM_LIBRARIES: 1
      - image: registry.opensuse.org/obs/server/unstable/container/sle12/sp3/images/x86_64/openbuildservice/mariadb:latest
        command: /usr/lib/mysql/mysql-systemd-helper start
        name: db
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: cd src/api; bundle install --jobs=3 --retry=3 --path vendor/bundle
      - run:
          name: Wait for DB
          command: mysqladmin ping -h db
      - run:
          name: Setup application
          command: cd src/api; bundle exec rake dev:bootstrap RAILS_ENV=test
      - run:
          name: Run rspec
          command: cd src/api; bundle exec rspec
  minitest:
    docker:
      - image: registry.opensuse.org/obs/server/unstable/container/sle12/sp3/images/x86_64/openbuildservice/frontend-backend:latest
        environment:
          NOKOGIRI_USE_SYSTEM_LIBRARIES: 1
          NO_MEMCACHED: 1
      - image: registry.opensuse.org/obs/server/unstable/container/sle12/sp3/images/x86_64/openbuildservice/mariadb:latest
        command: /usr/lib/mysql/mysql-systemd-helper start
        name: db
      - image: registry.opensuse.org/obs/server/unstable/container/sle12/sp3/images/x86_64/openbuildservice/memcached:latest
        name: cache
    steps:
      - checkout
      - run:
          name: Init submodule
          command: git submodule update --init --recursive --remote
      - run:
          name: Install dependencies
          command: cd src/api; bundle install --jobs=3 --retry=3 --path vendor/bundle
      - run:
          name: Wait for DB
          command: mysqladmin ping -h db
      - run:
          name: Setup application
          command: cd src/api; bundle exec rake dev:bootstrap[old_test_suite] RAILS_ENV=test
      - run:
          name: Run minitest
          command: cd src/api; bundle exec rake test:api
      - run:
          name: Run spider
          command: cd src/api; bundle exec rake test:api
  backend:
    docker:
      - image: registry.opensuse.org/obs/server/unstable/container/sle12/sp3/images/x86_64/openbuildservice/backend:latest
    steps:
      - checkout
      - run:
          name: Init submodule
          command: git submodule update --init --recursive --remote
      - run:
          name: backend
          command: make -C src/backend test

workflows:
  version: 2
  test_all:
    jobs:
      - rspec
      - minitest
      - backend
